name: PlayerSpy
description: Player Spy is a player surveillance plugin that can record the movements and interactions of a player with the world, creatures, and players.
version: 1.5.2

author: Schmoller

main: au.com.mineauz.PlayerSpy.SpyPlugin

commands:
  playerspy:
    description: Container command for all player spy commands 
    usage: /<command> <spy | stopspy | list | playback | help> [args] 
    aliases: ps
  honeypot:
    description: Allows you to define and modify honeypots
    aliases: hp
permissions:
  playerspy.basic:
    description: Provides read only commands and abilities.
    default: false
    children:
      playerspy.playback: true
      playerspy.help: true
      playerspy.inspect: true
      playerspy.search: true
      playerspy.inventory: true
      playerspy.enderchest: true
      playerspy.list: true
      playerspy.catchup: true
      
  playerspy.normal:
    description: Provides all commands and abilities for normal admin use.
    default: false
    children:
      playerspy.basic: true
      playerspy.spy: true
      playerspy.rollback: true
      playerspy.restore: true
      playerspy.inventory.edit: true
      playerspy.enderchest.edit: true
      playerspy.honeypot: true
      playerspy.honeypot.immune: true
  
  playerspy.op:
    description: Provides every ability.
    default: op
    children:
      playerspy.normal: true
      playerspy.purge: true
      playerspy.reload: true
      playerspy.integritycheck: true
  
  playerspy.*:
    default: op
    children:
      playerspy.op: true

  playerspy.spy:
    default: op
    description: Allows a player to record the movements and activities of a player.
  playerspy.playback:
    default: op
    description: Allows a player to playback the movements and activities of a player.
  playerspy.list:
    default: op
    description: Allows a player to list all active recordings
  playerspy.help:
    default: op
    description: Allows a player to view the help
  playerspy.purge:
    default: op
    description: Allows a player to purge records
  playerspy.inspect:
    default: op
    description: Allows a player to inspect changes
  playerspy.search:
    default: op
    description: Allows a player to search through the logs
  playerspy.reload:
    default: op
    description: Allows a player to reload the config file
  playerspy.rollback:
    default: op
    description: Allows a player to rollback changes
  playerspy.restore:
    default: op
    description: Allows a player to restore changes that were undone with rollback
  playerspy.inventory:
    default: op
    description: Allows a player to view another players inventory
  playerspy.inventory.edit:
    default: op
    description: Allows a player to modify another players inventory
    children:
      playerspy.inventory: true
  playerspy.enderchest:
    default: op
    description: Allows a player to view another players enderchest
  playerspy.enderchest.edit:
    default: op
    description: Allows a player to modify another players enderchest
    children:
      playerspy.inventory: true
  playerspy.catchup:
    default: op
    description: Allows a player to use the catchup command
  playerspy.integritycheck:
    default: op
    description: Allows a player to check the integrity of data files
  playerspy.honeypot:
    default: op
    description: Allows a player to place and modify honeypots
  playerspy.honeypot.immune:
    default: op
    descripton: Players with this permission are immune from honeypots
